name: CI Code Quality
on:
  pull_request:

permissions: {}

jobs:
  code-quality:
    name: ğŸ§ª Code Quality Checks
    runs-on: ubuntu-latest
    container:
      image: reinhuddev1/code-quality:latest
    
    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v4
        
      - name: ğŸ§ª Run pre-commit
        run: pre-commit run --all-files
