name: ðŸ§ª Code Quality
on:
  workflow_call:

jobs:
  code-quality:
    name: ðŸ§ª Code Quality Checks
    runs-on: ubuntu-latest
    container:
      image: reinhuddev1/code-quality:latest
    
    steps:
      - name: ðŸ“¦ Checkout
        uses: actions/checkout@v4

      - name: âœ… Run pre-commit
        run: |
          cp /app/.pre-commit-config.yaml .
          pre-commit install-hooks
          pre-commit run --all-files
